// apps/docs/src/components/code-editor/index.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import { dromeState } from "$stores/drome.svelte.js";
  import { createCodeMirror } from "$lib/utils/codemirror/index.js";
  import IconPause20 from "$icons/icon-pause-20.svelte";
  import IconPlay20 from "$icons/icon-play-20.svelte";
  import IconRefresh20 from "$icons/icon-refresh-20.svelte";
  import type { EditorView } from "codemirror";
  import "$lib/utils/codemirror/theme.css";

  interface Props {
    code: string;
  }

  let { code }: Props = $props();

  const id = crypto.randomUUID();
  let editor = $state<EditorView | null>(null);
  let containerRef = $state<HTMLDivElement | null>(null);

  const isActive = $derived(id === dromeState.activeEditor);
  const isPlaying = $derived(!dromeState.paused && isActive);
  const isQueued = $derived(dromeState.queued && isActive);

  $effect(() => {
    if (!browser || !containerRef) return;
    editor = createCodeMirror(containerRef, code.trim());
    return () => editor?.destroy();
  });

  function play() {
    if (!dromeState.paused) dromeState.queued = true;
    if (!dromeState.drome || !editor) return;
    dromeState.drome.evaluate(editor.state.doc.toString());
    dromeState.drome.start();
    dromeState.activeEditor = id;
  }

  function stop() {
    dromeState.drome?.stop();
  }

  function togglePlay() {
    if (isPlaying) stop();
    else play();
  }
</script>

<div>
  <div class="header">
    <div>
      <button onclick={togglePlay} disabled={isQueued}>
        {#if isPlaying}
          <IconPause20 />
        {:else}
          <IconPlay20 />
        {/if}
      </button>
      <button onclick={play} disabled={!isPlaying || isQueued}>
        <IconRefresh20 />
      </button>
    </div>
    {#if isQueued}
      <span class="queued">Queued</span>
    {/if}
  </div>
  <div bind:this={containerRef} class="editor"></div>
</div>

<style>
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--spacing-2) var(--spacing-3);
    border: 1px solid var(--app-color-border-subtle);
    border-block-end: none;
    border-radius: var(--spacing-2) var(--spacing-2) 0 0;
  }

  .header button {
    display: inline-flex;
    align-items: center;
    background: none;
    border: none;
    padding: var(--spacing-1_5);
  }

  .editor {
    border: 1px solid var(--app-color-border-subtle);
    border-radius: 0 0 var(--spacing-2) var(--spacing-2);
    overflow: clip;
  }

  .queued {
    display: inline-block;
    font-size: 0.75rem;
    font-weight: 500;
    color: var(--app-color-fg-secondary);
    padding: 0 var(--spacing-2) 1px;
  }
</style>

// apps/docs/src/components/code-editor/index.tsx
import { createSignal, onMount, createUniqueId } from "solid-js";
import { useStore } from "@nanostores/solid";

import IconPause20 from "@/components/icons/icon-pause-20";
import IconPlay20 from "@/components/icons/icon-play-20";
import { drome, paused, queued, activeEditor } from "@/stores/drome";
import { createCodeMirror } from "@/utils/codemirror";

import type { EditorView } from "codemirror";

import "@/utils/codemirror/theme.css";
import s from "./style.module.css";
import IconRefresh20 from "../icons/icon-refresh-20";

function CodeEditor(props: { code: string }) {
  const id = createUniqueId();
  const [editor, setEditor] = createSignal<EditorView | null>(null);
  const $drome = useStore(drome);
  const $paused = useStore(paused);
  const $queued = useStore(queued);
  const $activeEditor = useStore(activeEditor);
  let containerRef: HTMLDivElement | undefined;

  const isActive = () => id === $activeEditor();
  const isPlaying = () => !$paused() && isActive();
  const isQueued = () => $queued() && isActive();

  onMount(() => {
    if (!containerRef) return;

    setEditor(createCodeMirror(containerRef, props.code.trim()));
  });

  function play() {
    if (!$paused()) queued.set(true);
    const ed = editor();
    const d = $drome();
    if (!d || !ed) return;
    d.evaluate(ed.state.doc.toString());
    d.start();
    activeEditor.set(id);
  }

  function stop() {
    $drome()?.stop();
  }

  function togglePlay() {
    if (isPlaying()) stop();
    else play();
  }

  return (
    <div>
      <div class={s.header}>
        <div>
          <button onClick={togglePlay} disabled={isQueued()}>
            {isPlaying() ? <IconPause20 /> : <IconPlay20 />}
          </button>
          <button onClick={play} disabled={!isPlaying() || isQueued()}>
            <IconRefresh20 />
          </button>
        </div>
        {isQueued() && <span class={s.queued}>Queued</span>}
      </div>
      <div ref={containerRef} class={s.editor} />
    </div>
  );
}

export default CodeEditor;
