// apps/docs/src/components/table-of-contents/index.svelte
<script lang="ts">
  interface Heading {
    depth: number;
    slug: string;
    text: string;
  }

  interface Props {
    headings: Heading[];
  }

  const SCROLL_Y_OFF = 40;

  let { headings }: Props = $props();

  const filtered = $derived(
    headings.filter((h) => h.depth >= 2 && h.depth <= 3),
  );
  let activeId = $state<string | null>(null);

  $effect(() => {
    const headings = filtered; // reactive dependency — re-runs on navigation
    activeId = headings[0]?.slug ?? null;

    const headingEls = [
      ...document.querySelectorAll<HTMLElement>(
        "article h2[id], article h3[id]",
      ),
    ];

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          activeId = entry.target.id;
        }
      },
      { rootMargin: "0px 0px -66% 0px" },
    );

    headingEls.forEach((h) => observer.observe(h));
    return () => observer.disconnect();
  });

  function scrollTo(e: MouseEvent, slug: string) {
    e.preventDefault();
    const target = document.getElementById(slug);
    if (!target) return;
    const root = document.documentElement;
    const rem = parseFloat(getComputedStyle(root).fontSize);
    const headerHeight =
      parseFloat(
        getComputedStyle(root).getPropertyValue("--app-editor-header-height"),
      ) * rem;
    const top =
      target.getBoundingClientRect().top +
      window.scrollY -
      headerHeight -
      SCROLL_Y_OFF;
    window.scrollTo({ top, behavior: "smooth" });
    history.pushState(null, "", `#${slug}`);
  }
</script>

{#if filtered.length > 0}
  <nav>
    <p class="label">On this page</p>
    <ul class="list">
      {#each filtered as heading (heading.slug)}
        <li class:depth3={heading.depth === 3}>
          <a
            href="#{heading.slug}"
            class:active={activeId === heading.slug}
            onclick={(e) => scrollTo(e, heading.slug)}
          >
            {heading.text}
          </a>
        </li>
      {/each}
    </ul>
  </nav>
{/if}

<style>
  .label {
    font-family: monospace;
    font-size: var(--font-size-4xs);
    letter-spacing: 0.15em;
    text-transform: uppercase;
    color: var(--app-color-fg-tertiary);
    margin-block-end: var(--spacing-3);
  }

  .list {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: var(--spacing-1);
  }

  .list a {
    display: block;
    font-size: var(--font-size-xs);
    color: var(--app-color-fg-tertiary);
    text-decoration: none;
    line-height: 1.4;
    padding-block: var(--spacing-0_5);
  }

  .list a:hover {
    color: var(--app-color-fg-primary);
  }

  .list a.active {
    color: var(--app-color-accent-primary);
  }

  .depth3 a {
    padding-inline-start: var(--spacing-3);
  }
</style>

// apps/docs/src/components/table-of-contents/index.tsx
import { createSignal, onCleanup, onMount, For, Show } from "solid-js";
import s from "./style.module.css";

interface Heading {
  depth: number;
  slug: string;
  text: string;
}

function TableOfContents(props: { headings: Heading[] }) {
  const filtered = () =>
    props.headings.filter((h) => h.depth >= 2 && h.depth <= 3);
  const [activeId, setActiveId] = createSignal<string | null>(
    filtered()[0].slug,
  );

  onMount(() => {
    const headingEls = [
      ...document.querySelectorAll<HTMLElement>(
        "article h2[id], article h3[id]",
      ),
    ];

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setActiveId(entry.target.id);
        }
      },
      { rootMargin: "0px 0px -66% 0px" },
    );

    headingEls.forEach((h) => observer.observe(h));
    onCleanup(() => observer.disconnect());
  });

  return (
    <Show when={filtered().length > 0}>
      <nav>
        <p class={s.label}>On this page</p>
        <ul class={s.list}>
          <For each={filtered()}>
            {(heading) => (
              <li class={heading.depth === 3 ? s.depth3 : undefined}>
                <a
                  href={`#${heading.slug}`}
                  class={activeId() === heading.slug ? s.active : undefined}
                  onClick={(e) => {
                    e.preventDefault();
                    const target = document.getElementById(heading.slug);
                    if (!target) return;
                    const top =
                      target.getBoundingClientRect().top + window.scrollY - 48;
                    window.scrollTo({ top, behavior: "smooth" });
                    history.pushState(null, "", `#${heading.slug}`);
                  }}
                >
                  {heading.text}
                </a>
              </li>
            )}
          </For>
        </ul>
      </nav>
    </Show>
  );
}

export default TableOfContents;
